function aboutpiv_Callback(~, ~, ~)
string={...
	'PIVlab - 用于 MATLAB 的时间分辨数字粒子图像测速工具';...
	['版本：' gui.retr('PIVver')];...
	'';...
	'由 Dr. William Thielicke 和 Prof. Dr. Eize J. Stamhuis 开发';...
	'以 MIT 许可证发布。';...
	'';...
	'';...
	'首次发布于 2010 年 3 月 9 日';...
	'';...
	'http://www.PIVlab.de';...
	'联系方式：PIVlab@gmx.com';...
	'';...
	'开发主要发生在 William 的业余时间。';...
	'但由于他现在在一家开发 PIV 设备的公司工作，';...
	'他的一部分工作时间用于改进 PIVlab。因此，';...
	'该开发部分由 www.OPTOLUTION.com 赞助。';

	};
gui.custom_msgbox('msg',getappdata(0,'hgui'),'关于',string,'modal',{'OK'},'OK');