function MainWindow_CloseRequestFcn(hObject, ~, ~)
handles=gui.gethand;
batchModeActive=gui.retr('batchModeActive');
yes_synonyms = { ...
    '绝对要', ...
    '当然要', ...
    '是的', ...
    '没错', ...
    '肯定要', ...
    '确实要', ...
    '一定', ...
    '对', ...
    '嗯', ...
    '好', ...
    '要', ...
    '必须的', ...
    '没问题', ...
    '放心', ...
    '收到', ...
    '必须啊', ...
    '请退出', ...
    'Si señor', ...
    };
yes=yes_synonyms{randi(numel(yes_synonyms))};
no_synonyms = { ...
    '不了', ...
    '不', ...
    '不要', ...
    '不行', ...
    '不同意', ...
    '绝不', ...
    '不太想', ...
    '绝对不', ...
    '无论如何都不', ...
    '不，先生', ...
    '今天不行', ...
    '大概不行', ...
    '不了谢谢', ...
    '我想不行', ...
    };
no=no_synonyms{randi(numel(no_synonyms))};

if batchModeActive == 0
    figure(hObject);drawnow
    button=gui.custom_msgbox('quest',getappdata(0,'hgui'),'退出？','您要退出 PIVlab 吗？','modal',{yes no},no);
else
    button = yes;
end
try
    gui.toolsavailable(1)
catch
end
if strcmp(button,yes)==1
    try
        homedir=gui.retr('homedir');
        pathname=gui.retr('pathname');
        save('PIVlab_settings_default.mat','homedir','pathname','-append');
        %save last settings in acquisition menu
        last_selected_device = get(handles.ac_config, 'value');
        last_selected_fps = get(handles.ac_fps,'Value');
        last_selected_pulsedist = get(handles.ac_interpuls,'String');
        last_selected_energy =get(handles.ac_power,'String');
        save('PIVlab_settings_default.mat','last_selected_device','last_selected_fps','last_selected_pulsedist','last_selected_energy','-append');
        selected_com_port = gui.retr('selected_com_port');
        if ~isempty(selected_com_port)
            save('PIVlab_settings_default.mat','selected_com_port','-append');
        end
    catch
    end
    try
        PIVlab_capture_lensctrl (1400,1400,0) %lens needs to be set to neutral otherwise re-enabling power might cause issues
    catch
    end
    try
        hgui = getappdata(0,'hgui');
        serpo=getappdata(hgui,'serpo');
        string3='WarningSignDisable!';
        pause(1)
        writeline(serpo,string3); %disable the lighting of the laser warning sign
        pause(0.5)
    catch
    end
    try
        second_monitor_fig = gui.retr('second_monitor_fig');
        if ~isempty(second_monitor_fig) && isvalid(second_monitor_fig)
            delete(second_monitor_fig);
        end
    catch
    end
    try
        delete(hObject);
    catch
        close(gcf,'force');
    end
end